#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Exercise02.Resource", IsApplication=true)]

namespace Exercise02
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cardElevation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cardMaxElevation = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cardUseCompatPadding = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int contentPadding = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int contentPaddingBottom = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int contentPaddingLeft = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int contentPaddingRight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int contentPaddingTop = 2130771977;
			
			// aapt resource value: 0x7f01000b
			public const int layoutManager = 2130771979;
			
			// aapt resource value: 0x7f01000d
			public const int reverseLayout = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public const int spanCount = 2130771980;
			
			// aapt resource value: 0x7f01000e
			public const int stackFromEnd = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int cardview_dark_background = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cardview_light_background = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cardview_shadow_end_color = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int cardview_shadow_start_color = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int cardview_compat_inset_shadow = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int cardview_default_elevation = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int cardview_default_radius = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int elevation_card = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int hight_icon = 2131099660;
			
			// aapt resource value: 0x7f060003
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int item_touch_helper_swipe_escape_max_velocity = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int item_touch_helper_swipe_escape_velocity = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int margin_large = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int margin_medium = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int margin_small = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int padding_medium = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int radius_card = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int width_icon = 2131099661;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cart1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int menu = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int minus1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int plus1 = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int image = 2131165186;
			
			// aapt resource value: 0x7f070010
			public const int imagebtn_cart = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int imagebtn_menu = 2131165201;
			
			// aapt resource value: 0x7f070000
			public const int item_touch_helper_previous_elevation = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout1 = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int linearLayout2 = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int linearLayout3 = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int linearLayout4 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int minus = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int name = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public const int plus = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int recyclerView1 = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int toolbar1 = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int tv_amount = 2131165196;
			
			// aapt resource value: 0x7f070006
			public const int tv_priceperunit = 2131165190;
			
			// aapt resource value: 0x7f07000f
			public const int tv_sum = 2131165199;
			
			// aapt resource value: 0x7f070007
			public const int tv_unit = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int tv_value = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CardView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CardViewBill = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Cart = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080000
			public const int app_name = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040001
			public const int Base_CardView = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int CardView = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int CardView_Dark = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int CardView_Light = 2130968579;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
